const translations = {
  es: {
    // Nav & Common
    title: "MotoGroup | Rodar acompañado, nunca solo",
    nav_features: "Features",
    nav_sos: "SOS",
    nav_community: "Community",
    nav_plans: "Plans",
    nav_support: "Support",
    nav_legal: "Legal",
    nav_download: "Download App",
    nav_back: "Volver al Inicio",
    footer_tag: "Precision Engineered for the Road.",
    foot_priv: "Política de Privacidad",
    foot_term: "Términos de Servicio",
    foot_cook: "Política de Cookies",
    foot_safe: "Safety Guidelines",
    foot_copy: "© 2026 MotoGroup. All rights reserved.",
    
    // Index Page
    desc: "MotoGroup: Rastreo GPS en vivo, telemetría de rodada, alertas de emergencia visibles para todos los integarntes de una rodada, álbumes de recuerdo grupales para volver a vivir las rodadas, muchas funciones más.",
    hero_badge: "Live Now: 1,242 Bikers Online",
    hero_title: "Rodar acompañado, <span class='accent'>nunca solo.</span>",
    hero_desc: "Rastreo GPS en vivo, telemetría de rodada, alertas de emergencia visibles para todos los integarntes de una rodada, álbumes de recuerdo grupales para volver a vivir las rodadas, muchas funciones más.",
    app_store_get: "Consíguelo en el",
    google_play_get: "DISPONIBLE EN",
    hero_partners: "COMODIDAD PARA:",
    features_title: "Tecnología de Vanguardia",
    features_sub: "Diseñado para la precisión en el asfalto. Cada módulo está optimizado para darte control absoluto.",
    feat_gps_title: "Tracking GPS en Grupo",
    feat_gps_desc: "Visualiza a todos tus compañeros en tiempo real con un mapa optimizado para alta velocidad y baja latencia.",
    feat_sos_title: "Alertas SOS",
    feat_sos_desc: "Alertas de un toque, para marcar mensajes en la ruta, visibles para todos los integrantes de una rodada.",
    sos_pulse: "Monitoreo Activo",
    feat_poi_title: "Puntos de Interés",
    feat_poi_desc: "Diferentes modalidades de visualización de tu posición y la de los integrantes en una rodada activa.",
    feat_album_title: "Recuerdos",
    feat_album_desc: "Albumes de recuerdos con mucha, mucha, mucha información de una rodada. Fotografias individuales y de los integrantes de una rodada, para que vuelvas a vivir esos momentos.",
    feat_gam_title: "Gamificación",
    feat_gam_desc: "Recorre carreteras, acumula kilómetros en tus viajes y desbloquea equipo legendario. Cada rodada suma kilómetros para desbloquear tus logros.",
    gam_badge: "DIAMANTE",
    feat_off_title: "Soporte Offline",
    feat_off_desc: "Optimizado para funcionar incluso si tu conexión falla en esos lugares donde la señal no es muy buena.",
    sos_label: "Protocolo de Seguridad",
    sos_title: "Seguridad sin Concesiones.",
    sos_f1_title: "Sensor de Colisión G-Force",
    sos_f1_desc: "Algoritmo inteligente que detecta desaceleraciones bruscas e impactos, activando una cuenta regresiva de 30 segundos antes de alertar.",
    sos_f2_title: "Difusión en Tiempo Real",
    sos_f2_desc: "En caso de emergencia, una alerta se envía a todos los integrantes de una rodada.",
    sim_title: "Simulación de Alerta",
    sim_sub: "Si no cancelas en <span id='sos-timer'>00:30</span>, se enviará señal SOS.",
    sim_sending: "Enviando Alerta...",
    sim_status: "PENDIENTE",
    sim_loc_label: "Ubicación Actual",
    sim_btn: "CANCELAR ALERTA",
    plans_title: "Elige tu nivel de rodada",
    plan_monthly: "Mensual",
    plan_annual: "Anual (-50%)",
    plan_free_desc: "Podrás unirte a rodadas de usuarios PRO",
    pf_1: "2 Creaciones de rodadas propias al mes",
    pf_2: "Tracking GPS propio y amigos",
    pf_3: "5 Fotos propias para revivir recuerdos",
    pf_4: "",
    btn_free: "EMPEZAR GRATIS",
    plan_prem_badge: "RECOMENDADO",
    plan_prem_desc: "La experiencia total de seguridad y comunidad sin límites.",
    pp_1: "Creación de rodadas ilimitadas",
    pp_2: "Tracking GPS propio y amigos",
    pp_3: "10 Fotos propias para revivir recuerdos",
    pp_4: "Recuerdos compartidos (mira todas las fotos que subió todo el grupo)",
    pp_5: "Telemetría avanzada, velocidad, altitud, aceleración, inclinación y más",
    btn_prem: "UNIRSE AL CLUB",
    contact_title: "Contacto Técnico",
    contact_desc: "¿Necesitas ayuda con el registro de tu Club o tienes dudas técnicas? Nuestro equipo de ingenieros está listo.",
    form_name: "Nombre",
    form_email: "Email",
    form_type: "Tipo de Consulta",
    ft_1: "Soporte Técnico",
    ft_2: "Registro de Club / Grupo",
    ft_3: "Ventas Premium Corporativas",
    ft_4: "Reportar un fallo",
    form_msg: "Mensaje",
    form_btn: "ENVIAR MENSAJE",
    form_sending: "ENVIANDO...",
    form_success: "¡Mensaje enviado con éxito! Nos pondremos en contacto contigo pronto.",
    form_error: "Hubo un error al enviar el mensaje. Por favor intenta de nuevo.",
    plan_period_forever: "/siempre",
    plan_period_month: "/mes",
    plan_period_year: "/año",
    
    // Privacy Page
    priv_page_title: "Política de Privacidad | MotoGroup",
    priv_h1: "Política de Privacidad",
    update_date: "Última actualización: 27 de julio de 2026",
    priv_intro: "En <strong>MotoGroup</strong>, entendemos que la privacidad es tan importante como la seguridad en el camino. Esta Política de Privacidad describe cómo recopilamos, usamos y protegemos su información cuando utiliza nuestra aplicación móvil, sitio web y servicios relacionados (colectivamente, el 'Servicio').",
    priv_h2_1: "1. Información que Recopilamos",
    priv_p1: "Para brindarle la mejor experiencia de rodada en grupo, recopilamos los siguientes tipos de información:",
    priv_li1_1: "<strong>Datos de Ubicación (GPS):</strong> Recopilamos datos de ubicación precisos en tiempo real para habilitar el seguimiento en grupo, las alertas SOS y la telemetría. Esta información solo se comparte con su grupo autorizado durante una rodada activa.",
    priv_li1_2: "<strong>Telemetría y Movimiento:</strong> Usamos los sensores de su dispositivo (acelerómetro, giroscopio) para medir la velocidad, inclinación y detectar posibles colisiones (Fuerza G) para activar el protocolo de seguridad SOS.",
    priv_li1_3: "<strong>Información de la Cuenta:</strong> Nombre, dirección de correo electrónico, fotografía de perfil e información sobre su motocicleta para personalizar su experiencia y álbumes.",
    priv_li1_4: "<strong>Contenido del Usuario:</strong> Fotos compartidas en los álbumes grupales, mensajes de estado y puntos de interés (POIs) creados durante la ruta.",
    priv_h2_2: "2. Cómo Usamos su Información",
    priv_p2: "Utilizamos la información recopilada para:",
    priv_li2_1: "Facilitar la visualización en tiempo real de los integrantes de su rodada.",
    priv_li2_2: "Activar y gestionar las <strong>Alertas SOS</strong> en caso de emergencias o detección de accidentes.",
    priv_li2_3: "Generar estadísticas de rodada, telemetría y desbloquear logros en el sistema de Gamificación.",
    priv_li2_4: "Compilar los álbumes de recuerdos grupales.",
    priv_li2_5: "Mejorar y optimizar nuestros algoritmos de detección de colisiones y mapas offline.",
    priv_h2_3: "3. Compartir Información",
    priv_p3: "La seguridad y la comunidad son el núcleo de MotoGroup. Compartimos su información de la siguiente manera:",
    priv_li3_1: "<strong>Con su Grupo de Rodada:</strong> Su ubicación en tiempo real, alertas SOS y contenido del álbum solo son visibles para los miembros del grupo al que se haya unido.",
    priv_li3_2: "<strong>Contactos de Emergencia:</strong> En caso de una alerta SOS no cancelada, podemos enviar su última ubicación conocida a los contactos de emergencia que haya designado.",
    priv_li3_3: "<strong>Proveedores de Servicio:</strong> Podemos compartir datos anonimizados con servicios de terceros que nos ayudan a proporcionar infraestructura (como servidores en la nube y servicios de mapas).",
    priv_h2_4: "4. Seguridad de los Datos",
    priv_p4: "Implementamos medidas de seguridad de vanguardia para proteger sus datos personales contra acceso, alteración, divulgación o destrucción no autorizados. Sin embargo, ninguna transmisión por Internet es 100% segura, por lo que recomendamos tomar precauciones al compartir información sensible.",
    priv_h2_5: "5. Sus Derechos",
    priv_p5: "Usted tiene el derecho de acceder, corregir o eliminar su información personal en cualquier momento a través de la configuración de la aplicación. También puede desactivar el seguimiento GPS cuando no esté en una rodada activa.",
    priv_h2_6: "6. Contacto",
    priv_p6: "Si tiene alguna pregunta sobre esta Política de Privacidad o sus datos, puede contactarnos en <strong>support@motogroup.net</strong>.",
    
    // Terms Page
    term_page_title: "Términos del Servicio | MotoGroup",
    term_h1: "Términos del Servicio",
    term_intro: "Bienvenido a <strong>MotoGroup</strong>. Al descargar, instalar o utilizar nuestra aplicación y servicios relacionados, usted acepta estar sujeto a estos Términos del Servicio. Lea cuidadosamente antes de comenzar a rodar con nosotros.",
    term_h2_1: "1. Uso del Servicio y Seguridad Vial",
    term_p1: "Nuestra prioridad es la seguridad en la ruta. Al usar MotoGroup, usted se compromete a:",
    term_li1_1: "Respetar siempre las leyes de tránsito y normas de seguridad vial de su jurisdicción.",
    term_li1_2: "No interactuar con la aplicación de forma que distraiga su atención de la conducción. Las alertas y el mapa deben usarse como referencia pasiva o mientras el vehículo está detenido.",
    term_li1_3: "Entender que MotoGroup es una herramienta de asistencia. Usted es el único responsable de su seguridad y la de su vehículo.",
    term_h2_2: "2. Funcionalidad de Alertas SOS y Sensor de Colisión",
    term_p2: "El sistema de Alertas SOS y el Sensor de Colisión G-Force están diseñados para proporcionar ayuda rápida en caso de emergencia. Sin embargo:",
    term_li2_1: "La efectividad de la alerta depende de la conectividad a la red móvil y del correcto funcionamiento de los sensores de su dispositivo.",
    term_li2_2: "No garantizamos que todas las caídas o impactos sean detectados.",
    term_li2_3: "La aplicación no sustituye a los servicios de emergencia oficiales (como el 911). Siempre contacte a las autoridades correspondientes en caso de un accidente grave.",
    term_h2_3: "3. Planes de Suscripción",
    term_p3: "MotoGroup ofrece un plan gratuito y un plan Premium. Al suscribirse a <strong>MotoGroup Premium</strong>, acepta los siguientes términos de pago:",
    term_li3_1: "Las suscripciones se renuevan automáticamente (mensual o anualmente) a menos que se cancelen con al menos 24 horas de antelación al final del período actual.",
    term_li3_2: "El plan Premium desbloquea funciones avanzadas como el SOS automático (Crash Detect), mapas offline y telemetría avanzada.",
    term_li3_3: "No se ofrecen reembolsos parciales por períodos no utilizados, pero puede seguir usando las funciones Premium hasta el final del ciclo de facturación.",
    term_h2_4: "4. Contenido del Usuario y Comunidad",
    term_p4: "Nuestra plataforma permite la creación de Álbumes de Recuerdos y Puntos de Interés (POIs). Usted es responsable del contenido que sube. Nos reservamos el derecho de eliminar cualquier contenido que consideremos ofensivo, peligroso o que infrinja los derechos de terceros.",
    term_h2_5: "5. Limitación de Responsabilidad",
    term_p5: "En la medida máxima permitida por la ley, MotoGroup y sus desarrolladores no serán responsables por ningún daño directo, indirecto, incidental o consecuente que resulte del uso o la incapacidad de usar nuestra aplicación, incluyendo accidentes de tráfico, fallas del hardware del teléfono, o pérdida de datos de telemetría y recuerdos grupales.",
    term_h2_6: "6. Cambios a los Términos",
    term_p6: "Nos reservamos el derecho de modificar estos términos en cualquier momento. Le notificaremos de cualquier cambio significativo a través de la aplicación o por correo electrónico.",

    // Cookie Page
    cook_page_title: "Política de Cookies | MotoGroup",
    cook_h1: "Política de Cookies",
    cook_intro: "En <strong>MotoGroup</strong>, utilizamos cookies y tecnologías similares para mejorar su experiencia en nuestra plataforma web y móvil. Esta Política de Cookies explica qué son, cómo las utilizamos y cómo puede gestionarlas.",
    cook_h2_1: "1. ¿Qué son las Cookies?",
    cook_p1: "Las cookies son pequeños archivos de texto que se almacenan en su dispositivo (computadora, teléfono o tablet) cuando visita un sitio web o utiliza una aplicación. Permiten que la plataforma recuerde sus acciones y preferencias durante un período de tiempo.",
    cook_h2_2: "2. Tipos de Cookies que Utilizamos",
    cook_p2: "Utilizamos las siguientes categorías de cookies para el funcionamiento de MotoGroup:",
    cook_li1_1: "<strong>Cookies Esenciales:</strong> Son estrictamente necesarias para el funcionamiento del servicio. Incluyen aquellas que le permiten iniciar sesión en su cuenta y garantizar la seguridad del sistema de tracking.",
    cook_li1_2: "<strong>Cookies de Rendimiento y Analítica:</strong> Nos ayudan a entender cómo los usuarios interactúan con nuestra aplicación y sitio web, recopilando datos estadísticos anónimos para mejorar nuestras funcionalidades.",
    cook_li1_3: "<strong>Cookies de Funcionalidad:</strong> Permiten que la plataforma recuerde sus preferencias, como el idioma elegido y la configuración de visualización del mapa.",
    cook_h2_3: "3. ¿Cómo Utilizamos las Cookies?",
    cook_p3: "Las utilizamos con los siguientes propósitos principales:",
    cook_li2_1: "Mantener su sesión activa de forma segura.",
    cook_li2_2: "Optimizar la velocidad de carga de los mapas y el servicio de telemetría.",
    cook_li2_3: "Personalizar la experiencia del usuario recordando sus rutas o grupos favoritos.",
    cook_li2_4: "Evaluar el rendimiento general de nuestra plataforma.",
    cook_h2_4: "4. Gestión y Desactivación de Cookies",
    cook_p4: "Puede configurar su navegador o dispositivo móvil para rechazar todas o algunas de las cookies. Sin embargo, tenga en cuenta que si desactiva las cookies esenciales, algunas funciones clave de MotoGroup (como mantener la sesión iniciada durante una rodada) podrían no funcionar correctamente.",
    cook_p5: "Para aprender a gestionar las cookies, visite el menú de configuración o ayuda de su navegador o dispositivo.",
    cook_h2_5: "5. Contacto",
    cook_p6: "Si tiene alguna duda o inquietud sobre nuestra Política de Cookies, por favor contáctenos en <strong>support@motogroup.net</strong>."
  },
  en: {
    // Nav & Common
    title: "MotoGroup | Ride together, never alone",
    nav_features: "Features",
    nav_sos: "SOS",
    nav_community: "Community",
    nav_plans: "Plans",
    nav_support: "Support",
    nav_legal: "Legal",
    nav_download: "Download App",
    nav_back: "Back to Home",
    footer_tag: "Precision Engineered for the Road.",
    foot_priv: "Privacy Policy",
    foot_term: "Terms of Service",
    foot_cook: "Cookie Policy",
    foot_safe: "Safety Guidelines",
    foot_copy: "© 2026 MotoGroup. All rights reserved.",

    // Index Page
    desc: "MotoGroup: Live GPS tracking, ride telemetry, emergency alerts visible to all ride members, group memory albums to relive your rides, and much more.",
    hero_badge: "Live Now: 1,242 Bikers Online",
    hero_title: "Ride together, <span class='accent'>never alone.</span>",
    hero_desc: "Live GPS tracking, ride telemetry, emergency alerts visible to all ride members, group memory albums to relive your rides, and much more.",
    app_store_get: "Download on the",
    google_play_get: "GET IT ON",
    hero_partners: "COMFORT FOR:",
    features_title: "Cutting-Edge Technology",
    features_sub: "Engineered for precision on the asphalt. Each module is optimized to give you absolute control.",
    feat_gps_title: "Group GPS Tracking",
    feat_gps_desc: "View all your companions in real-time with a map optimized for high speed and low latency.",
    feat_sos_title: "SOS Alerts",
    feat_sos_desc: "One-touch alerts to broadcast messages on the route, visible to all members of a ride.",
    sos_pulse: "Active Monitoring",
    feat_poi_title: "Points of Interest",
    feat_poi_desc: "Different viewing modes for your position and other members in an active ride.",
    feat_album_title: "Memories",
    feat_album_desc: "Memory albums with a ton of information from a ride. Individual and group photos to relive those moments.",
    feat_gam_title: "Gamification",
    feat_gam_desc: "Ride roads, accumulate kilometers on your trips, and unlock legendary gear. Every ride adds up to unlock your achievements.",
    gam_badge: "DIAMOND",
    feat_off_title: "Offline Support",
    feat_off_desc: "Optimized to work even if your connection drops in places where the signal isn't great.",
    sos_label: "Security Protocol",
    sos_title: "Security Without Compromise.",
    sos_f1_title: "G-Force Collision Sensor",
    sos_f1_desc: "Smart algorithm that detects sudden decelerations and impacts, triggering a 30-second countdown before alerting.",
    sos_f2_title: "Real-Time Broadcast",
    sos_f2_desc: "In an emergency, an alert is sent to all members of a ride.",
    sim_title: "Alert Simulation",
    sim_sub: "If you don't cancel in <span id='sos-timer'>00:30</span>, an SOS signal will be sent.",
    sim_sending: "Sending Alert...",
    sim_status: "PENDING",
    sim_loc_label: "Current Location",
    sim_btn: "CANCEL ALERT",
    plans_title: "Choose your ride level",
    plan_monthly: "Monthly",
    plan_annual: "Annual (-50%)",
    plan_free_desc: "You will be able to join PRO user rides",
    pf_1: "2 Personal ride creations per month",
    pf_2: "Personal and friends GPS tracking",
    pf_3: "5 Personal photos to relive memories",
    pf_4: "",
    btn_free: "START FOR FREE",
    plan_prem_badge: "RECOMMENDED",
    plan_prem_desc: "The total experience of safety and unlimited community.",
    pp_1: "Unlimited ride creations",
    pp_2: "Personal and friends GPS tracking",
    pp_3: "10 Personal photos to relive memories",
    pp_4: "Shared memories (view all photos uploaded by the entire group)",
    pp_5: "Advanced telemetry: speed, altitude, acceleration, lean angle, and more",
    btn_prem: "JOIN THE CLUB",
    contact_title: "Technical Support",
    contact_desc: "Need help registering your Club or have technical questions? Our engineering team is ready.",
    form_name: "Name",
    form_email: "Email",
    form_type: "Query Type",
    ft_1: "Technical Support",
    ft_2: "Club / Group Registration",
    ft_3: "Corporate Premium Sales",
    ft_4: "Report a bug",
    form_msg: "Message",
    form_btn: "SEND MESSAGE",
    form_sending: "SENDING...",
    form_success: "Message sent successfully! We will contact you soon.",
    form_error: "An error occurred while sending the message. Please try again.",
    plan_period_forever: "/forever",
    plan_period_month: "/month",
    plan_period_year: "/year",

    // Privacy Page
    priv_page_title: "Privacy Policy | MotoGroup",
    priv_h1: "Privacy Policy",
    update_date: "Last updated: July 27, 2026",
    priv_intro: "At <strong>MotoGroup</strong>, we understand that privacy is just as important as safety on the road. This Privacy Policy describes how we collect, use, and protect your information when you use our mobile application, website, and related services (collectively, the 'Service').",
    priv_h2_1: "1. Information We Collect",
    priv_p1: "To provide you with the best group riding experience, we collect the following types of information:",
    priv_li1_1: "<strong>Location Data (GPS):</strong> We collect precise real-time location data to enable group tracking, SOS alerts, and telemetry. This information is only shared with your authorized group during an active ride.",
    priv_li1_2: "<strong>Telemetry and Motion:</strong> We use your device's sensors (accelerometer, gyroscope) to measure speed, lean angle, and detect possible collisions (G-Force) to trigger the SOS security protocol.",
    priv_li1_3: "<strong>Account Information:</strong> Name, email address, profile picture, and information about your motorcycle to personalize your experience and albums.",
    priv_li1_4: "<strong>User Content:</strong> Photos shared in group albums, status messages, and points of interest (POIs) created during the route.",
    priv_h2_2: "2. How We Use Your Information",
    priv_p2: "We use the collected information to:",
    priv_li2_1: "Facilitate real-time visualization of your ride members.",
    priv_li2_2: "Trigger and manage <strong>SOS Alerts</strong> in case of emergencies or accident detection.",
    priv_li2_3: "Generate ride statistics, telemetry, and unlock achievements in the Gamification system.",
    priv_li2_4: "Compile group memory albums.",
    priv_li2_5: "Improve and optimize our collision detection algorithms and offline maps.",
    priv_h2_3: "3. Sharing Information",
    priv_p3: "Safety and community are the core of MotoGroup. We share your information as follows:",
    priv_li3_1: "<strong>With Your Ride Group:</strong> Your real-time location, SOS alerts, and album content are only visible to the members of the group you have joined.",
    priv_li3_2: "<strong>Emergency Contacts:</strong> In the event of an uncancelled SOS alert, we may send your last known location to the emergency contacts you have designated.",
    priv_li3_3: "<strong>Service Providers:</strong> We may share anonymized data with third-party services that help us provide infrastructure (such as cloud servers and mapping services).",
    priv_h2_4: "4. Data Security",
    priv_p4: "We implement state-of-the-art security measures to protect your personal data against unauthorized access, alteration, disclosure, or destruction. However, no internet transmission is 100% secure, so we recommend taking precautions when sharing sensitive information.",
    priv_h2_5: "5. Your Rights",
    priv_p5: "You have the right to access, correct, or delete your personal information at any time through the app settings. You can also disable GPS tracking when you are not on an active ride.",
    priv_h2_6: "6. Contact",
    priv_p6: "If you have any questions about this Privacy Policy or your data, you can contact us at <strong>support@motogroup.net</strong>.",

    // Terms Page
    term_page_title: "Terms of Service | MotoGroup",
    term_h1: "Terms of Service",
    term_intro: "Welcome to <strong>MotoGroup</strong>. By downloading, installing, or using our app and related services, you agree to be bound by these Terms of Service. Please read carefully before you start riding with us.",
    term_h2_1: "1. Use of Service and Road Safety",
    term_p1: "Our priority is safety on the road. By using MotoGroup, you agree to:",
    term_li1_1: "Always respect the traffic laws and road safety regulations of your jurisdiction.",
    term_li1_2: "Do not interact with the app in a way that distracts your attention from driving. The alerts and map should be used as passive reference or while the vehicle is stopped.",
    term_li1_3: "Understand that MotoGroup is an assistance tool. You are solely responsible for your safety and that of your vehicle.",
    term_h2_2: "2. SOS Alerts and Collision Sensor Functionality",
    term_p2: "The SOS Alerts system and G-Force Collision Sensor are designed to provide quick help in an emergency. However:",
    term_li2_1: "The effectiveness of the alert depends on mobile network connectivity and the proper functioning of your device's sensors.",
    term_li2_2: "We do not guarantee that all falls or impacts will be detected.",
    term_li2_3: "The app does not replace official emergency services (such as 911). Always contact the proper authorities in case of a serious accident.",
    term_h2_3: "3. Subscription Plans",
    term_p3: "MotoGroup offers a free plan and a Premium plan. By subscribing to <strong>MotoGroup Premium</strong>, you accept the following payment terms:",
    term_li3_1: "Subscriptions renew automatically (monthly or annually) unless canceled at least 24 hours before the end of the current period.",
    term_li3_2: "The Premium plan unlocks advanced features like auto SOS (Crash Detect), offline maps, and advanced telemetry.",
    term_li3_3: "No partial refunds are offered for unused periods, but you can continue to use Premium features until the end of the billing cycle.",
    term_h2_4: "4. User Content and Community",
    term_p4: "Our platform allows the creation of Memory Albums and Points of Interest (POIs). You are responsible for the content you upload. We reserve the right to remove any content we deem offensive, dangerous, or that infringes on the rights of third parties.",
    term_h2_5: "5. Limitation of Liability",
    term_p5: "To the maximum extent permitted by law, MotoGroup and its developers shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use our app, including traffic accidents, phone hardware failures, or loss of telemetry data and group memories.",
    term_h2_6: "6. Changes to Terms",
    term_p6: "We reserve the right to modify these terms at any time. We will notify you of any significant changes via the app or email.",

    // Cookie Page
    cook_page_title: "Cookie Policy | MotoGroup",
    cook_h1: "Cookie Policy",
    cook_intro: "At <strong>MotoGroup</strong>, we use cookies and similar technologies to enhance your experience on our web and mobile platform. This Cookie Policy explains what they are, how we use them, and how you can manage them.",
    cook_h2_1: "1. What are Cookies?",
    cook_p1: "Cookies are small text files that are stored on your device (computer, phone, or tablet) when you visit a website or use an application. They allow the platform to remember your actions and preferences over a period of time.",
    cook_h2_2: "2. Types of Cookies We Use",
    cook_p2: "We use the following categories of cookies for the operation of MotoGroup:",
    cook_li1_1: "<strong>Essential Cookies:</strong> These are strictly necessary for the operation of the service. They include those that allow you to log into your account and ensure the security of the tracking system.",
    cook_li1_2: "<strong>Performance and Analytics Cookies:</strong> They help us understand how users interact with our app and website, collecting anonymous statistical data to improve our features.",
    cook_li1_3: "<strong>Functionality Cookies:</strong> They allow the platform to remember your preferences, such as the chosen language and map display settings.",
    cook_h2_3: "3. How We Use Cookies?",
    cook_p3: "We use them for the following main purposes:",
    cook_li2_1: "To keep your session active securely.",
    cook_li2_2: "To optimize the loading speed of maps and telemetry service.",
    cook_li2_3: "To personalize the user experience by remembering your favorite routes or groups.",
    cook_li2_4: "To evaluate the overall performance of our platform.",
    cook_h2_4: "4. Cookie Management and Disabling",
    cook_p4: "You can configure your browser or mobile device to reject all or some cookies. However, please note that if you disable essential cookies, some key features of MotoGroup (like staying logged in during a ride) may not function properly.",
    cook_p5: "To learn how to manage cookies, visit the settings or help menu of your browser or device.",
    cook_h2_5: "5. Contact",
    cook_p6: "If you have any questions or concerns about our Cookie Policy, please contact us at <strong>support@motogroup.net</strong>."
  }
};

let currentLang = localStorage.getItem('lang') || 'es';

function updateLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('lang', lang);
  document.documentElement.lang = lang;
  
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang][key]) {
      el.innerHTML = translations[lang][key];
    }
  });
  
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (translations[lang][key]) {
      el.placeholder = translations[lang][key];
    }
  });

  const metaDesc = document.getElementById('meta-desc');
  if (metaDesc && translations[lang].desc) metaDesc.content = translations[lang].desc;

  document.querySelectorAll('.lang-toggle').forEach(btn => {
    btn.textContent = lang === 'es' ? 'ENG' : 'ES';
  });

  if (typeof updatePricingPeriod === 'function') {
    updatePricingPeriod();
  }
}

document.addEventListener('DOMContentLoaded', () => {
  const toggleLangButtons = document.querySelectorAll('.lang-toggle');
  toggleLangButtons.forEach(btn => {
    btn.addEventListener('click', () => {
      updateLanguage(currentLang === 'es' ? 'en' : 'es');
    });
  });

  updateLanguage(currentLang);
});
